### ISSUE TITLE
Programm doesn't starts

### ISSUE THREAD

**Issue by Chaoschaot232** [kuba6000/GTNH-Jenkins-Downloader#3]
I don't know what's going wrong but after downloading the latest EXE and unblocking because of stupied SmartScreen it created
C:\Users\Marcel\AppData\Roaming\GTNHJenksinsDownloader with GTNHJenkinsDownloader.exe and Newtonsoft.Json.dll but after shortly showing "Downloading Dependencies" the window closes instantly and nothing else is opened.

I have no logs, or other information which I could share, only that I can provide these ones:

Edition	Windows 11 Pro
Version	22H2
Installed on	‎22/‎05/‎2022
OS build	22622.575
Experience	Windows Feature Experience Pack 1000.22634.1000.0

Either smth. goes wrongly from my side or smth. else within the programm isn't working anymore. Any hlep or updates to this one would be nice :)

**Comment by kuba6000** [comment]
I will look into that

**Comment by kuba6000** [comment]
https://github.com/kuba6000/GTNH-Jenkins-Downloader/releases/tag/v0.6
Should be fixed
